post:
  tags:
    - ContaDigital
  summary: Retorna a permissão de cadastro pelo App
  operationId: ContaDigital_ConsultarConfiguracoesApp
  parameters:
    - name: Content-Type
      in: header
      required: true
      schema:
        type: string
        default: application/json
    - name: UserName
      in: header
      required: true
      schema:
        type: string
    - name: Authorization
      in: header
      required: true
      schema:
        type: string
    - name: RequestOrigin
      in: header
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../components/schemas/ConsultarConfiguracoesAppSingleRequest.yaml
      text/json:
        schema:
          $ref: ../components/schemas/ConsultarConfiguracoesAppSingleRequest.yaml
      application/xml:
        schema:
          $ref: ../components/schemas/ConsultarConfiguracoesAppSingleRequest.yaml
      text/xml:
        schema:
          $ref: ../components/schemas/ConsultarConfiguracoesAppSingleRequest.yaml
      application/x-www-form-urlencoded:
        schema:
          $ref: ../components/schemas/ConsultarConfiguracoesAppSingleRequest.yaml
    required: true
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: >-
              ../components/schemas/ConsultarConfiguracoesAppSingleResponseData.yaml
        text/json:
          schema:
            $ref: >-
              ../components/schemas/ConsultarConfiguracoesAppSingleResponseData.yaml
        application/xml:
          schema:
            $ref: >-
              ../components/schemas/ConsultarConfiguracoesAppSingleResponseData.yaml
        text/xml:
          schema:
            $ref: >-
              ../components/schemas/ConsultarConfiguracoesAppSingleResponseData.yaml
  x-codegen-request-body-name: request
