required:
  - CodigoCanal
type: object
properties:
  CodigoCanal:
    type: integer
    description: "Código do canal\r\n<br />"
    format: int32
    default: 0
description: Request para a consulta permissão de cadastro pelo App
xml:
  name: ConsultarConfiguracoesAppRequestData
