type: object
properties:
  Data:
    $ref: ./ConsultarConfiguracoesAppResponseData.yaml
  ResultCode:
    type: integer
    format: int32
  Message:
    type: string
  ValidationData:
    $ref: ./ValidationData.yaml
description: ''
xml:
  name: ConsultarConfiguracoesAppSingleResponseData
